"""A concise homepage and the research-led path for a brand built from scratch."""

def home_routes():
    return '''<section class="home-direction" id="wybierz-kierunek"><div class="container direction-layout"><div><p class="eyebrow">CO CHCESZ ZMIENIĆ?</p><h2>Twoja marka.<br><em>Twój następny krok.</em></h2></div><div class="direction-copy"><p>Firma z historią czy pomysł, który dopiero dojrzewa? Zaczniemy tam, gdzie jesteś. Połączymy strategię, stronę i marketing w jeden kierunek.</p><div class="direction-choices"><a href="/o-donie.html#przemiana">Chcę odnowić markę <span aria-hidden="true">↗</span></a><a href="/o-donie.html#od-zera">Chcę zbudować ją od zera <span aria-hidden="true">↗</span></a></div><a class="text-link" href="/oferta.html">Poznaj zakres współpracy <span aria-hidden="true">↗</span></a></div></div></section>
<section class="home-discover container" aria-label="Odkryj projekty i agentów"><a class="discover-projects" href="/realizacje.html"><div class="discover-art"><img class="discover-main-image" src="/assets/live/janusz-original.webp" width="1600" height="1078" loading="lazy" alt="Fotografia z projektu Edward Janusz"><img class="discover-postcard" src="/assets/live/silver-pt-4-3-a.webp" width="1200" height="773" loading="lazy" alt="Pocztówka ze zbioru Silver & Glass"></div><p class="eyebrow">PROJEKTY / EDWARD JANUSZ · SILVER &amp; GLASS</p><div class="discover-title"><h2>Historie, w które<br><em>chce się wejść.</em></h2><span aria-hidden="true">↗</span></div><p>Odkryj działające serwisy i pomysły dla różnych branż.</p></a>
<a class="discover-agents" href="/automatyzacja.html"><p class="eyebrow">DONA / AGENCI AI</p><h2>Oddaj rutynę.<br><em>Zachowaj kontrolę.</em></h2><div class="discover-flow" aria-hidden="true"><span class="discover-flow-in">Nowe zapytanie</span><i></i><span class="discover-flow-draft">Szkic odpowiedzi</span><i></i><span class="discover-flow-review">Twoja decyzja <b>✓</b></span></div><p>Zobacz, jak pracują agenci poczty, mediów i stron WWW.</p><span class="discover-action">Uruchom przykład <span aria-hidden="true">↗</span></span></a></section>
<section class="home-invitation"><div class="container invitation-layout"><h2>To co,<br><em>porozmawiamy?</em></h2><div><p>O pomyśle, który chodzi Ci po głowie.<br>Albo o stronie, z której chcesz być dumny.</p><a class="button primary" href="/kontakt.html">Opowiedz nam o nim <span aria-hidden="true">↗</span></a><a class="invitation-phone" href="tel:+48573569141">+48 573 569 141</a></div></div></section>'''

FOUNDATION = [
    ('Research', 'Najpierw<br>poznajemy grunt.', 'Badamy rynek, potrzeby odbiorców i konkurencję. Sprawdzamy, jak klienci podejmują decyzje i co może wyróżnić Twój pomysł.', 'Wnioski z researchu: odbiorcy, konkurencja, szanse i pytania do sprawdzenia.', [
        ('Odbiorcy', 'Czego potrzebują?', 'Problemy, oczekiwania, język i droga do zakupu.'),
        ('Konkurencja', 'Co już mają do wyboru?', 'Oferty, komunikacja i doświadczenie klienta.'),
        ('Twój biznes', 'Gdzie jest miejsce dla Ciebie?', 'Kompetencje, zasoby i hipotezy, które warto zweryfikować.')]),
    ('Strategia', 'Z wiedzy<br>wybieramy kierunek.', 'Określamy, do kogo mówisz, jaką wartość dajesz i dlaczego klient ma wybrać właśnie Ciebie. Przekładamy wnioski na decyzje o marce.', 'Strategia marki: pozycjonowanie, obietnica, wyróżniki i kluczowe komunikaty.', [
        ('Odbiorca', 'Dla kogo jesteś?', 'Konkretny klient i potrzeba, na którą odpowiadasz.'),
        ('Obietnica', 'Co zmieniasz na lepsze?', 'Wartość, którą klient rozumie i której potrzebuje.'),
        ('Wiarygodność', 'Dlaczego ma Ci zaufać?', 'Prawdziwe argumenty i dowody za Twoją ofertą.')]),
    ('Plan działania', 'Wiemy co.<br>Ustalamy jak.', 'Wybieramy priorytety, kanały i kolejność prac. Dopasowujemy zakres do budżetu oraz ustalamy, po czym poznamy, że działania mają sens.', 'Plan uruchomienia: zakres, harmonogram, budżet i sposób mierzenia efektów.', [
        ('Priorytety', 'Co robimy najpierw?', 'Oferta, treści i funkcje potrzebne na start.'),
        ('Kanały', 'Gdzie spotkasz klientów?', 'Strona, wyszukiwarka i wybrane media społecznościowe.'),
        ('Pomiar', 'Co będziemy sprawdzać?', 'Zapytania, droga do kontaktu i wyniki uzgodnionych działań.')]),
    ('Marka i start', 'Pomysł zyskuje<br>własną formę.', 'Tworzymy nazwę i identyfikację w uzgodnionym zakresie, piszemy treści, projektujemy stronę i przygotowujemy komunikację. Uruchamiamy całość i obserwujemy pierwsze reakcje.', 'Spójny zestaw na start: identyfikacja, treści, strona i materiały do uzgodnionych kanałów.', [
        ('Tożsamość', 'Tak wygląda Twoja marka.', 'Nazwa, znak, kolory i język komunikacji.'),
        ('Doświadczenie', 'Tak poznaje Cię klient.', 'Strona, oferta i wygodny kontakt.'),
        ('Obecność', 'Tak wychodzisz do ludzi.', 'Materiały startowe, publikacja i pierwsze działania marketingowe.')])
]

def brand_foundation():
    tabs = ''.join(f'<button type="button" role="tab" id="foundation-tab-{i}" aria-controls="foundation-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" data-foundation-tab="{i}"><span>0{i+1}</span>{name}</button>' for i,(name,*_) in enumerate(FOUNDATION))
    panels = ''
    for i,(name,title,desc,result,topics) in enumerate(FOUNDATION):
        nodes=''.join(f'<div class="foundation-topic"><span>{label}</span><h4>{question}</h4><p>{detail}</p></div>' for label,question,detail in topics)
        panels += f'''<div class="foundation-panel" id="foundation-panel-{i}" role="tabpanel" aria-labelledby="foundation-tab-{i}" tabindex="0" data-foundation-panel="{i}" ><div class="foundation-focus"><span class="foundation-number" aria-hidden="true">0{i+1}</span><h3>{title}</h3><p>{desc}</p></div><div class="foundation-canvas"><div class="foundation-topics">{nodes}</div><div class="foundation-collect" aria-hidden="true"><svg viewBox="0 0 720 110" preserveAspectRatio="none"><path d="M120 0V20Q120 45 145 45H335Q360 45 360 70V110M360 0V110M600 0V20Q600 45 575 45H385Q360 45 360 70"/></svg></div><div class="foundation-result"><span>CO OTRZYMUJESZ</span><p>{result}</p></div><div class="foundation-brand-visual"><img src="/assets/studio/architecture-small.webp" width="960" height="540" loading="lazy" alt="Koncepcyjny projekt marki architektonicznej Horyzont"><div><span>PRZYKŁAD KONCEPCYJNY / OD PYTAŃ DO PROJEKTU</span><strong>horyzont.</strong><p>Przestrzeń<br>ma znaczenie.</p></div></div></div></div>'''
    return f'''<section class="foundation-section" id="od-zera" data-foundation><div class="container"><div class="foundation-heading"><div><p class="eyebrow">A JEŚLI DOPIERO ZACZYNASZ?</p><h2>Z pomysłu<br><em>w markę.</em></h2></div><div><p>Nie musisz mieć jeszcze nazwy, logo ani strony. Potrzebujesz pomysłu, któremu warto nadać kierunek.</p><p>Zaczynamy od dobrych pytań i rzetelnego researchu. Projekt wyrasta ze strategii i planu.</p></div></div><div class="foundation-tabs" role="tablist" hidden aria-label="Etapy budowania marki od zera">{tabs}</div>{panels}<div class="foundation-footer"><p>Zakres badań i prac ustalamy z Tobą przed rozpoczęciem.</p><a class="text-link" href="/kontakt.html?temat=Nowa%20marka">Zaplanujmy początek Twojej marki <span aria-hidden="true">↗</span></a></div></div></section>'''

def strategy_offer():
    return '''<section class="strategy-offer section" id="strategia"><div class="container strategy-layout"><div><p class="eyebrow">RESEARCH / STRATEGIA / NOWA MARKA</p><h2>Masz pomysł.<br><em>Zbudujmy fundament.</em></h2><a class="text-link" href="/o-donie.html#od-zera">Zobacz, jak powstaje marka <span aria-hidden="true">↗</span></a></div><div><p class="lead">Zanim powstanie pierwszy projekt, poznajemy rynek i odbiorców. Pomagamy wybrać kierunek, ułożyć ofertę i zaplanować wejście marki na rynek.</p><p>Research konkurencji i klientów, strategia marki, plan działania, identyfikacja, treści i strona — dobieramy zakres do etapu Twojego pomysłu.</p><a class="button dark" href="/kontakt.html?temat=Nowa%20marka">Porozmawiajmy o Twoim pomyśle <span aria-hidden="true">↗</span></a></div></div></section>'''
