"""Full-bleed brand scenes and authentic interactive project presentations."""

def spring_opening():
    return '''<section class="spring-opening" data-spring-opening>
<div class="spring-backdrop" aria-hidden="true"><picture><source media="(max-width:700px)" srcset="/assets/spring/bloom-mobile.webp"><img src="/assets/spring/bloom.webp" width="1672" height="941" alt="" fetchpriority="high"></picture><video muted playsinline preload="none" data-spring-video data-desktop="/assets/spring/awakening-desktop.mp4" data-small="/assets/spring/awakening-mobile.mp4"></video></div>
<div class="spring-copy container"><p class="eyebrow">PROBATUM / STRONY WWW · MARKETING · AI</p><h1>Daj swojej<br>marce<br><span>nowe życie.</span></h1><p>Odważny początek albo nowy rozdział.<br>Zbudujmy go razem.</p><div class="button-row"><a class="button primary" href="/kontakt.html">Zacznijmy nowy rozdział <span aria-hidden="true">↗</span></a><a class="text-link" href="/oferta.html">Poznaj ofertę <span aria-hidden="true">↗</span></a></div></div>
<div class="spring-bottom container"><a class="spring-next" href="#wybierz-kierunek">Znajdź swój kierunek <span aria-hidden="true">↓</span></a><button type="button" class="scene-motion" data-spring-toggle hidden>Odtwórz przemianę <span aria-hidden="true">▶</span></button></div></section>'''

def live_projects(uid='live',heading=True):
    head='''<div class="container live-heading"><p class="eyebrow">WYBRANE PROJEKTY / DZIAŁAJĄCE SERWISY</p><h2>Nie tylko oglądaj.<br><span class="muted">Daj się wciągnąć.</span></h2><p>Odkryj fragment każdego projektu. A potem wejdź na stronę i zobacz całość.</p></div>''' if heading else ''
    return f'''<section class="live-projects" data-live-projects id="{uid}">{head}
<article class="live-project live-janusz project" data-category="live" data-case="janusz">
<div class="container live-meta"><span><i aria-hidden="true"></i> DZIAŁAJĄCY SERWIS</span><span>01 / HISTORIA I FOTOGRAFIA</span><a href="https://www.edwardjanusz.pl/" target="_blank" rel="noopener">edwardjanusz.pl ↗</a></div>
<div class="live-composition container"><div class="live-copy"><p class="live-kicker">Cyfrowa opowieść o rzeszowskim atelier</p><h2>Edward<br><em>Janusz.</em></h2><p>Archiwalne fotografie, historia ludzi i miejsca, które można odkrywać na nowo.</p><div class="live-feature-list"><span>Katalog fotografii</span><span>Opowieści o miejscach</span><span>Interaktywne porównania</span></div><a class="button dark" href="https://www.edwardjanusz.pl/" target="_blank" rel="noopener">Wejdź w tę historię <span aria-hidden="true">↗</span></a></div>
<div class="live-art"><div class="history-photo" data-history-photo><img class="history-original" src="/assets/live/janusz-original.webp" width="1600" height="1078" loading="lazy" alt="Oryginalna fotografia witryny zakładu E. Janusz w Rzeszowie"><img class="history-colour" src="/assets/live/janusz-color.webp" width="1600" height="893" loading="lazy" alt="Witryna zakładu E. Janusz — koloryzacja AI dostępna na stronie projektu" aria-hidden="true"><div class="history-caption" aria-hidden="true"><span data-history-mode>ORYGINAŁ</span><span>DZF:1:58</span></div></div><div class="history-control"><button type="button" data-history-toggle aria-pressed="false">Ożyw kolor <span aria-hidden="true">↗</span></button><span>Przykład funkcji serwisu</span></div><p class="live-note">Koloryzacja AI jest interpretacją. Oryginał pozostaje dostępny do porównania.</p></div></div>
<div class="container live-foot"><p>Historia podana tak, by chciało się zostać na dłużej.</p><a class="text-link" href="/kontakt.html?temat=Strona%20internetowa">Porozmawiajmy o Twojej stronie <span aria-hidden="true">↗</span></a></div></article>
<article class="live-project live-silver project" data-category="live" data-case="silver">
<div class="container live-meta"><span><i aria-hidden="true"></i> DZIAŁAJĄCY SERWIS</span><span>02 / KOLEKCJA I ODKRYWANIE</span><a href="https://www.silverandglass.pl/" target="_blank" rel="noopener">silverandglass.pl ↗</a></div>
<div class="live-composition container"><div class="live-copy"><p class="live-kicker">Pocztówki, fotografie, zapisane historie</p><h2>Silver<br><em>&amp; Glass.</em></h2><p>Od miasta do jednej pocztówki. Od obrazu do wiadomości zapisanej na odwrocie.</p><div class="live-feature-list"><span>Kolekcje miast</span><span>Awers i rewers</span><span>Wyszukiwanie w zbiorze</span></div><a class="button dark" href="https://www.silverandglass.pl/" target="_blank" rel="noopener">Odkryj kolekcję <span aria-hidden="true">↗</span></a></div>
<div class="live-art"><div class="postcard-stage" data-postcard-stage><img class="postcard-wing wing-left" src="/assets/live/silver-pt-3-21-a.webp" width="1600" height="1028" loading="lazy" alt="Pocztówka z Bramą Floriańską ze zbioru Silver & Glass"><img class="postcard-wing wing-right" src="/assets/live/silver-pt-4-3-a.webp" width="1600" height="1031" loading="lazy" alt="Pocztówka z trzema widokami Krakowa ze zbioru Silver & Glass"><div class="postcard-turn" data-postcard-turn><img class="postcard-face front" src="/assets/live/silver-pt-3-79-a.webp" width="1600" height="1086" loading="lazy" alt="Awers pocztówki: Barbakan i Brama Floriańska w Krakowie" data-postcard-front><img class="postcard-face back" src="/assets/live/silver-pt-3-79-b.webp" width="1600" height="1114" loading="lazy" alt="Rewers tej samej pocztówki z Barbakanem" data-postcard-back aria-hidden="true"></div></div><div class="postcard-control"><div><span class="mini-label">KRAKÓW / PT:3:79</span><p data-postcard-side>Awers · Barbakan i Brama Floriańska</p></div><button type="button" data-postcard-flip aria-pressed="false">Odwróć pocztówkę <span aria-hidden="true">↻</span></button></div><p class="live-note">Oryginalne skany z kolekcji. Obróć kartę i zajrzyj na drugą stronę.</p></div></div>
<div class="container live-foot"><p>Duży zbiór. Prosta droga do własnego odkrycia.</p><a class="text-link" href="/kontakt.html?temat=Strona%20internetowa">Stwórzmy miejsce dla Twojego pomysłu <span aria-hidden="true">↗</span></a></div></article></section>'''

APPROACH_STEPS = [
 ('Poznajemy','Każda firma<br>ma swój charakter.','Zaczynamy od ludzi, historii i oferty. Szukamy tego, co warto zachować — i zrozumieć lepiej.'),
 ('Rozkładamy','Rozumiemy<br>każdy element.','Przyglądamy się marce, stronie, komunikacji i drodze klienta. Sprawdzamy, gdzie coś przestało ze sobą współpracować.'),
 ('Odnawiamy','Przywracamy<br>pełnię możliwości.','Porządkujemy ofertę i treści. Projektujemy wizerunek, kontakt oraz narzędzia dopasowane do sposobu pracy firmy.'),
 ('Łączymy','Twój charakter.<br>Nowa siła.', 'Składamy stronę, marketing i automatyzację w spójne doświadczenie. Sprawdzamy całą drogę — od pierwszego wrażenia do rozmowy.')
]

def restoration_scene():
    chapters=''.join(f'<div class="restoration-chapter" data-restoration-chapter="{i}" {"hidden" if i else ""}><span>0{i+1} / {label.upper()}</span><h2>{title}</h2><p>{desc}</p>{"<a class=\"text-link\" href=\"/kontakt.html\">Pokaż nam swoją firmę <span aria-hidden=\"true\">↗</span></a>" if i==3 else ""}</div>' for i,(label,title,desc) in enumerate(APPROACH_STEPS))
    nav=''.join(f'<button type="button" data-restoration-step="{i}" aria-pressed="{str(i==0).lower()}"><span>0{i+1}</span>{label}<i aria-hidden="true"></i></button>' for i,(label,_,_) in enumerate(APPROACH_STEPS))
    return f'''<section class="restoration restoration-static" data-stage="0" data-restoration id="przemiana"><div class="restoration-sticky"><div class="restoration-media" aria-hidden="true"><img class="restoration-poster" src="/assets/approach/restored.webp" width="1672" height="941" alt="" fetchpriority="high"><video muted playsinline preload="none" data-restoration-video data-desktop="/assets/approach/restoration-desktop.mp4" data-small="/assets/approach/restoration-mobile.mp4"></video></div>
<div class="restoration-intro container"><p class="eyebrow">PROBATUM / NASZE PODEJŚCIE</p><h1>Charakter zostaje.<br><span>Reszta nabiera blasku.</span></h1><p>Tak myślimy o nowym rozdziale Twojej firmy.</p></div>
<div class="restoration-labels" aria-hidden="true"><span>OFERTA</span><span>WIZERUNEK</span><span>DOŚWIADCZENIE KLIENTA</span></div>
<div class="restoration-narrative container">{chapters}</div><div class="restoration-bottom container"><div class="restoration-steps" aria-label="Etapy podejścia Probatum">{nav}</div><button type="button" data-restoration-mode class="scene-motion" hidden>Odtwórz przemianę <span aria-hidden="true">▶</span></button></div><div class="restoration-scroll" data-restoration-hint><a href="#jak-pracujemy">Poznaj nasze podejście <span aria-hidden="true">↓</span></a></div></div></section>
<section class="restoration-meaning section" id="jak-pracujemy"><div class="container two-columns"><div><p class="eyebrow">CO TO OZNACZA DLA TWOJEJ FIRMY?</p><h2>To, co wartościowe,<br><span class="muted">zostaje z Tobą.</span></h2></div><div><p class="lead">Twoja firma ma doświadczenie, klientów i własny sposób działania. To fundament. Pomagamy przełożyć go na markę, stronę i komunikację, które pokazują jej dzisiejszą wartość.</p><a class="button primary" href="/kontakt.html">Porozmawiajmy o Twojej firmie <span aria-hidden="true">↗</span></a></div></div></section>'''
