"""Reviewed public copy. Applied at build time, including shared markup."""

REVISIONS = {
    '<span aria-hidden="true">✓</span>': '',
    '<b>✓</b>': '',
    'Przywracamy<br>pełnię możliwości.': 'Porządkujemy<br>ofertę i wizerunek.',
    'Z wiedzy<br>wybieramy kierunek.': 'Ustalamy,<br>co Cię wyróżni.',
    'Określamy, do kogo mówisz, jaką wartość dajesz i dlaczego klient ma wybrać właśnie Ciebie. Przekładamy wnioski na decyzje o marce.': 'Określamy odbiorców, zalety oferty i powody, dla których klient może wybrać Twoją firmę.',
    'Badamy punkt wyjścia: ofertę, odbiorców, konkurencję i dotychczasowe działania. Wybieramy cel, który można ocenić.': 'Sprawdzamy ofertę, odbiorców, konkurencję i wyniki wcześniejszych reklam. Ustalamy, co ma przynieść kampania.',
    'Omówmy ten kierunek': 'Zapytaj o tę usługę',
    'Jaki jest cel<br>i punkt wyjścia?': 'Co planujesz<br>i na kiedy?',
    'Klient pisze. Proces rusza.': 'System odbiera wiadomość.',
    'Informacje znajdują swoje miejsce.': 'System zbiera dane do odpowiedzi.',
    'Nie zaczynasz od pustej kartki.': 'Agent przygotowuje szkic.',
    'Gotowy szkic. Ostatnie słowo należy do Ciebie.': 'Sprawdzasz i zatwierdzasz odpowiedź.',
    'Proces zbiera informacje o firmie i może przygotować dossier klienta.': 'Proces zbiera dostępne informacje o firmie i może przygotować podsumowanie dotyczące klienta.',
    'Jedno centrum. Wiele specjalizacji.': 'Agent wybiera potrzebne narzędzia.',
    'Nagranie, spotkanie lub wideo jest punktem wyjścia do zadania.': 'Przekazujesz nagranie i opisujesz, co chcesz z nim zrobić.',
    'Centrum tej gałęzi wybiera narzędzia odpowiednie do polecenia. Nie musi używać wszystkich.': 'Agent dobiera narzędzia do polecenia. Korzysta tylko z potrzebnych.',
    'Wywiad i materiały są punktem wyjścia do pracy nad stroną.': 'Opisujesz firmę, planowaną stronę i dostępne materiały.',
    'Z pomysłu powstaje coś konkretnego.': 'Agent przygotowuje materiały.',
    'Strona i marketing zaczynają współpracować.': 'Analiza strony i kampanii.',
    'Gałąź WWW i kampanii dobiera narzędzia do zadania. To mapa możliwości, nie automatyczna obietnica gotowego projektu.': 'Agent dobiera narzędzia do zadania. Zakres prac i sposób sprawdzania projektu ustalamy przed wdrożeniem.',
    'Dobry design.<br>Jasny przekaz.<br>Wspólny kierunek.': 'Strony internetowe,<br>marketing i automatyzacje<br>dla Twojej firmy.',
    'Teraz<br><em>Twój ruch.</em>': 'Porozmawiajmy<br><em>o Twojej firmie.</em>',
    'Strona, marketing i narzędzia mogą pracować na tę samą markę. Zaczynamy od Twojej firmy. Łączymy to, co widzi klient, z tym, czego potrzebuje biznes.': 'Projektujemy strony, prowadzimy kampanie i usprawniamy obsługę zapytań. Najpierw poznajemy Twoją ofertę i klientów, żeby ustalić, od czego warto zacząć.',
    'Ty tworzysz.<br><em>Rutyna robi się sama.</em>': 'Mniej powtarzania.<br><em>Więcej czasu na pracę.</em>',
    'O stronie, z której chcesz być dumny. O marce, która ma się wyróżniać. Albo o pomyśle, który dopiero nabiera kształtu.': 'Chcesz odnowić stronę, zaplanować reklamę albo rozpocząć nową działalność? Opowiedz nam o tym.',
    'Strona, która pokazuje<br><em>Twoją wartość.</em>': 'Pokaż klientom,<br><em>co oferujesz.</em>',
    'Zaczniemy od oferty i odbiorców. Zaprojektujemy oprawę oraz drogę od pierwszego wrażenia do zapytania.': 'Uporządkujemy ofertę, napiszemy treści i zaprojektujemy stronę, na której klient łatwo znajdzie usługę i kontakt.',
    'Zbadamy rynek, odbiorców i konkurencję. Ułożymy pozycjonowanie, plan i spójną formę Twojej nowej marki.': 'Sprawdzimy rynek i konkurencję. Ustalimy, do kogo kierujesz ofertę, czym się wyróżnisz i jak zaprezentujesz nową firmę.',
    'Poznamy obecną firmę. Wydobędziemy jej mocne strony i uporządkujemy to, co dziś utrudnia pokazanie jej wartości.': 'Przejrzymy ofertę, stronę i dotychczasowe materiały. Ustalimy, co zachować, a co zmienić, żeby lepiej przedstawiały Twoją firmę.',
    'Połączymy przekaz, reklamę i stronę po kliknięciu. Wybierzemy kanały, cel i sposób mierzenia działań.': 'Przygotujemy reklamy i stronę, na którą trafią zainteresowani. Ustalimy budżet, odbiorców i sposób oceny kampanii.',
    'Wybierzemy powtarzalne zadanie. Zaplanujemy przepływ informacji i miejsca, w których decyzja pozostaje po Twojej stronie.': 'Wybierzemy zadanie do automatyzacji, połączymy potrzebne programy i ustalimy, które działania wymagają Twojej zgody.',
    'MOŻLIWOŚCI, KTÓRE MOŻEMY POŁĄCZYĆ.': 'ZAKRES USŁUG',
    'Od pierwszej myśli<br><em>do pierwszego kontaktu.</em>': 'Czego potrzebuje<br><em>Twoja firma?</em>',
    'Nie. Zakres może obejmować pojedynczą usługę. Łączymy działania, kiedy wspólnie pomagają osiągnąć Twój cel.': 'Nie. Możesz zamówić samą stronę, kampanię lub automatyzację. Większy zakres ustalamy wtedy, gdy go potrzebujesz.',
    'Opowiedz krótko o firmie i planowanej zmianie. Ustalimy pytania, punkt wyjścia i następny krok.': 'Opowiedz krótko o firmie i tym, co chcesz zmienić. Dopytamy o potrzebne szczegóły i ustalimy dalsze kroki.',
    'Kierunek, który ma uzasadnienie': 'Oferta i treści',
    'Charakter, który rozpoznajesz': 'Projekt graficzny',
    'Poznajemy Twoją firmę i odbiorców. Układamy ofertę, hierarchię treści i drogę od wejścia na stronę do kontaktu.': 'Ustalamy, czego klienci szukają na Twojej stronie. Na tej podstawie układamy ofertę, treści i nawigację.',
    'Typografia, obrazy, kolor i ruch tworzą wspólną całość. Projekt pokazuje Twoją markę, a nie przypadkowy zestaw modnych efektów.': 'Dobieramy litery, zdjęcia, kolory i animacje do Twojej firmy. Pokazujemy projekt do oceny przed wdrożeniem.',
    'Piękna forma.<br><em>Przemyślana droga.</em>': 'Wygląd, treść<br><em>i wygodna obsługa.</em>',
    'Projekt obejmuje również to, co dzieje się po pierwszym „wow”.': 'Sprawdzamy czytelność oferty, nawigację i kontakt na komputerze oraz telefonie.',
    'Zakres, materiały, funkcje i termin wspólnie ustalamy przed wyceną. Otrzymujesz propozycję prac i harmonogram — bez zgadywania jednej ceny dla wszystkich firm.': 'Cena zależy od liczby podstron, treści, funkcji i integracji. Po omówieniu projektu otrzymasz wycenę i harmonogram.',
    'Łączymy pomysł, reklamę i drogę do Twojej firmy.': 'Planujemy kampanie, przygotowujemy reklamy i sprawdzamy, czy przynoszą zapytania.',
    'Właściwy przekaz.<br><em>Właściwy moment.</em>': 'Od planu kampanii<br><em>do oceny wyników.</em>',
    'Projektujemy całą drogę': 'Przygotowujemy reklamę i stronę',
    'Kreacja przyciąga uwagę. Strona rozwija tę samą obietnicę i pomaga podjąć decyzję. Kontakt domyka doświadczenie.': 'Reklama przedstawia ofertę. Strona po kliknięciu wyjaśnia szczegóły i pozwala wysłać zapytanie lub zadzwonić.',
    'Od jednego pomysłu do spójnej obecności: reklamy, strony i publikacji.': 'Ten sam projekt wykorzystany w reklamie, na stronie i w mediach społecznościowych.',
    'Taką spójność chcę u siebie': 'Porozmawiajmy o kampanii',
    'Strona, która rozwija obietnicę': 'Strona dla Twojej kampanii',
    'Obrazy, które pracują razem': 'Grafiki i wideo',
    'Projektujemy grafiki, karuzele i krótkie formaty wideo. Dopasowujemy materiał do miejsca publikacji, zachowując wspólną tożsamość marki.': 'Przygotowujemy grafiki, karuzele i krótkie filmy. Dopasowujemy rozmiary i treść do kanału, zachowując kolory i styl Twojej firmy.',
    'Sprawdzamy uzgodnione dane i reakcje odbiorców. Kolejne publikacje rozwijają to, co ma znaczenie dla Twojej marki.': 'Sprawdzamy wyniki publikacji, pytania i reakcje odbiorców. Na tej podstawie proponujemy kolejne tematy.',
    'Zaczynamy od ludzi, historii i oferty. Szukamy tego, co warto zachować — i zrozumieć lepiej.': 'Poznajemy historię firmy, jej ofertę i klientów. Ustalamy, co warto zachować.',
    'Przywracamy<br><span>pełnię możliwości.</span>': 'Porządkujemy<br><span>ofertę i wizerunek.</span>',
    'Przyglądamy się marce, stronie, komunikacji i drodze klienta. Sprawdzamy, gdzie coś przestało ze sobą współpracować.': 'Przeglądamy stronę, treści i sposób obsługi zapytań. Szukamy niejasnych informacji, błędów i utrudnień dla klientów.',
    'Składamy stronę, marketing i automatyzację w spójne doświadczenie. Sprawdzamy całą drogę — od pierwszego wrażenia do rozmowy.': 'Łączymy stronę z reklamą i obsługą zapytań. Sprawdzamy, czy klient może znaleźć ofertę, wysłać wiadomość i otrzymać odpowiedź.',
    'Twoja firma ma doświadczenie, klientów i własny sposób działania. To fundament. Pomagamy przełożyć go na markę, stronę i komunikację, które pokazują jej dzisiejszą wartość.': 'Odnowa firmy nie wymaga odrzucenia wszystkiego. Zachowujemy rozpoznawalne elementy i dobre treści, a poprawiamy to, co nie odpowiada już obecnej ofercie.',
    'Nie musisz mieć jeszcze nazwy, logo ani strony. Potrzebujesz pomysłu, któremu warto nadać kierunek.': 'Możesz zacząć bez nazwy, logo i strony. Najpierw sprawdzimy Twój pomysł i potrzeby przyszłych klientów.',
    'Zaczynamy od dobrych pytań i rzetelnego researchu. Projekt wyrasta ze strategii i planu.': 'Badamy rynek i konkurencję. Potem planujemy ofertę, wizerunek i uruchomienie firmy.',
    'Prawdziwe argumenty i dowody za Twoją ofertą.': 'Doświadczenie, realizacje i informacje potwierdzające Twoje kompetencje.',
    'Strategia marki: pozycjonowanie, obietnica, wyróżniki i kluczowe komunikaty.': 'Strategia marki: odbiorcy, wyróżniki oferty i najważniejsze informacje dla klientów.',
    'Spójny zestaw na start: identyfikacja, treści, strona i materiały do uzgodnionych kanałów.': 'Materiały na start: logo i kolory, treści, strona oraz uzgodnione materiały reklamowe.',
    'Przekazujemy gotowy zakres i ustalenia dotyczące obsługi. Kolejne działania wynikają z Twoich potrzeb oraz obserwacji.': 'Publikujemy stronę i przekazujemy instrukcje obsługi. Ustalamy, czy potrzebujesz dalszej opieki lub kampanii.',
    'Firma z historią czy pomysł na nową? W obu przypadkach zaczynamy od dobrego poznania tematu.': 'Napisz, czym zajmuje się Twoja firma lub jaką działalność planujesz.',
    'Skrócona wizualizacja naszych workflowów.': 'Tak działają wybrane automatyzacje DONY.',
    'Mały start, sprawdzalne działanie': 'Pierwsze wdrożenie i testy',
    'Rozbudowa ma sens po sprawdzeniu pierwszego zakresu.': 'Po testach decydujemy, czy rozbudować proces.',
    'Integracje i uprawnienia ustalamy przed deklarowaniem zakresu.': 'Przed wyceną sprawdzamy dostępne integracje i potrzebne uprawnienia.',
    'Wiadomość. Materiał wideo. Pomysł na stronę. Jeden impuls uruchamia kolejne działania.': 'System może opracować wiadomość, przeanalizować nagranie lub pomóc przygotować materiały na stronę.',
    'Od pierwszego pytania do własnego rezultatu.': 'Naucz się korzystać z AI na zadaniach ze swojej pracy.',
    'Lepsze pytanie.<br><em>Lepszy początek.</em>': 'Jak napisać<br><em>dobre polecenie?</em>',
    'Wybierz zadanie. Zobacz, jak cel, kontekst i format zmieniają ogólne polecenie w użyteczny punkt wyjścia.': 'Wybierz zadanie i porównaj krótką prośbę z poleceniem, które podaje potrzebne informacje i określa oczekiwaną odpowiedź.',
    'Poznajesz.<br>Robisz.<br><em>Sprawdzasz.</em>': 'Czego możesz<br><em>się nauczyć?</em>',
    'Pomysły i praktyczne przygotowanie materiałów z użyciem uzgodnionych narzędzi.': 'Przygotowanie tekstów, grafik i krótkich filmów z pomocą narzędzi AI.',
    'Jak rozpoznać powtarzalne zadanie i połączyć narzędzia wokół konkretnego celu.': 'Wybór zadania do automatyzacji, połączenie programów i sprawdzenie wyniku.',
    'Napisz, czym się zajmujesz i czego chcesz się nauczyć. Dobierzmy właściwy początek.': 'Napisz, czym się zajmujesz i czego chcesz się nauczyć. Pomożemy dobrać program.',
    'Praktyczne spojrzenie': 'Poradnik',
    'Prosto. Z konkretnym zastosowaniem.': 'Przeczytaj i sprawdź na własnym zadaniu.',
    'Małe zadanie. Jasna kolejność. Własny rezultat.': 'Instrukcje, które możesz przejść krok po kroku.',
    'Właśnie tam może być dobry początek.': 'Wybierz jedno takie zadanie do usprawnienia.',
    'Jeśli zadanie ma stałe reguły — na przykład zapisanie pól formularza i wysłanie powiadomienia — często wystarczy zwykła automatyzacja.': 'Przy stałych regułach często wystarczy zwykła automatyzacja, na przykład zapisanie danych formularza i wysłanie powiadomienia.',
    'Nie ma powodu dodawać modelu tylko po to, żeby nazwać rozwiązanie inteligentnym.': 'Do takiego zadania model AI nie jest potrzebny.',
    'interpretować nieustrukturyzowaną treść': 'zrozumieć treść wiadomości lub dokumentu',
    'Taki etap wymaga również zasad weryfikacji i obsługi niepewności.': 'Trzeba wtedy sprawdzać odpowiedzi i ustalić, co zrobić, gdy brakuje danych.',
    'Ustalimy możliwości bez zgadywania, jak działa jej zaplecze.': 'Sprawdzimy, z czym można ją połączyć.',
    'Poznaliśmy temat. Ustalamy cel i najważniejsze potrzeby.': 'Dopytamy o firmę i to, co chcesz zmienić.',
    'Sprawdzamy możliwy zakres i pytania wymagające wyjaśnienia.': 'Ustalimy potrzebne prace, materiały i termin.',
    'Dostajesz propozycję współpracy, zakres i wycenę.': 'Otrzymasz propozycję współpracy z zakresem i ceną.',
    'Nie potrzebujesz gotowego briefu. Wystarczą dwa zdania o firmie i tym, co chcesz zmienić.': 'Wystarczą dwa zdania o firmie i tym, co chcesz zmienić.',
    'To też jest<br>dobry punkt wyjścia.': 'Ustalimy go<br>podczas rozmowy.',
    'Jeśli nie znasz budżetu lub terminu, zostaw to otwarte.': 'Jeśli nie znasz budżetu lub terminu, wybierz „Do ustalenia” lub „Bez konkretnej daty”.',
    'Trzy krótkie kroki do zapytania o Twój projekt.': 'Opisz projekt, termin i budżet. Przygotujemy wiadomość do wysłania.',
    'Zaufanie zbudowane klarowną ofertą i profesjonalną oprawą.': 'Specjalizacje kancelarii, informacje o zespole i kontakt.',
    'Historia podana tak, by chciało się zostać na dłużej.': 'Fotografie można przeglądać w katalogu i poznawać w opisach miejsc.',
    'Duży zbiór. Prosta droga do własnego odkrycia.': 'Wybierz miasto, obejrzyj pocztówkę i przeczytaj jej odwrotną stronę.',
    'Twoja firma nie musi przypominać żadnego z tych przykładów. Zaprojektujmy jej własny charakter.': 'Porozmawiajmy o stronie dla Twojej branży i klientów.',
    'Dom otwiera się na światło i krajobraz. Prosta forma pozwala wybrzmieć materiałom. Przestrzeń zostawia miejsce na życie.': 'Duże przeszklenia otwierają salon na morze. Beton, drewno i kamień łączą wnętrze z otoczeniem.',
    'Naturalne materiały, miękkie światło i otwarcie na zewnątrz. Wnętrze zaprojektowane wokół codziennych rytuałów.': 'Drewniane wykończenia, jasny salon i wyjście na taras. Miejsce na wspólne posiłki i odpoczynek.',
    'Światło i naturalne materiały. Resztę dopiszesz Ty.': 'Jasny salon, naturalne materiały i widok na morze.',
    'Skopiowano ✓': 'Skopiowano',
    'Zaznaczono — skopiuj tekst': 'Tekst zaznaczony. Skopiuj go.',
    'Film niedostępny — pokazujemy obraz': 'Film niedostępny. Dostępne jest zdjęcie.',
    'To wizualizacja — żadna wiadomość nie jest wysyłana.': 'To pokaz. Wiadomość nie jest wysyłana.',
    'Agent przygotowuje, a Ty zachowujesz ostatnie słowo.': 'Możesz poprawić szkic i ponownie go ocenić.',
    'Probatum — ': 'Probatum | ',
    '01 — 02': '01 / 02',
}

def reviewed_copy(markup):
    for old, new in REVISIONS.items():
        markup = markup.replace(old, new)
    return markup

def reviewed_data(value):
    if isinstance(value, str):
        return reviewed_copy(value)
    if isinstance(value, list):
        return [reviewed_data(item) for item in value]
    if isinstance(value, tuple):
        return tuple(reviewed_data(item) for item in value)
    if isinstance(value, dict):
        return {key: reviewed_data(item) for key, item in value.items()}
    return value
