"""Shared Probatum art direction and interactive demonstrations, all statically rendered."""
import re
from pathlib import Path
from html import escape
from urllib.parse import quote
from cinematic import spring_opening, restoration_scene, live_projects
from brand_journey import brand_foundation
from flow_scene import flow_scene

ARROW = '<span aria-hidden="true">↗</span>'
import os
_OUT = os.environ.get('PROBATUM_OUT')
ASSETS = (Path(_OUT) if _OUT else Path(__file__).parent / 'dist') / 'assets/studio'

def link(text, url, primary=False):
    return f'<a class="{"button primary" if primary else "text-link"}" href="{url}">{text} {ARROW}</a>'

def contact(text='Porozmawiajmy', topic='', primary=True):
    return link(text, '/kontakt.html' + ('?temat='+quote(topic) if topic else ''), primary)

def picture(name='architecture', cls='', priority=False, alt='Koncepcyjna architektura: jasny dom nad morzem'):
    return f'<img class="{cls}" src="/assets/studio/{name}.webp" srcset="/assets/studio/{name}-small.webp 960w, /assets/studio/{name}.webp 1672w" sizes="(max-width:700px) 100vw, 85vw" width="1672" height="941" alt="{alt}" {"fetchpriority=high" if priority else "loading=lazy"}>'

def film(cls=''):
    if not (ASSETS/'architecture-desktop.mp4').exists():
        return ''
    return f'<video class="{cls}" muted playsinline preload="none" data-studio-film data-desktop="/assets/studio/architecture-desktop.mp4" data-small="/assets/studio/architecture-mobile.mp4" aria-hidden="true"></video>'

def heading(kicker, title, description='', action=''):
    return f'<section class="page-intro studio-intro"><div class="container"><p class="eyebrow">{kicker}</p><div class="intro-layout"><h1 data-reveal>{title}</h1><div class="intro-aside"><p>{description}</p>{action}</div></div></div></section>'

def closing(topic='', title='Teraz<br><em>Twój ruch.</em>', description='Pokaż nam swoją firmę. Ustalmy, co warto zmienić jako pierwsze.'):
    return f'<section class="studio-close" data-reveal><div class="container"><p class="eyebrow">MASZ POMYSŁ? ZACZNIJMY OD ROZMOWY.</p><div class="studio-close-grid"><h2>{title}</h2><div><p>{description}</p>{contact("Omówmy Twój projekt",topic)}<a class="close-phone" href="tel:+48573569141">+48 573 569 141 {ARROW}</a></div></div></div></section>'

def details(kicker, title, items, introduction=''):
    rows=''.join(f'<details {"open" if i==0 else ""}><summary><span>0{i+1}</span><h3>{name}</h3><b aria-hidden="true">+</b></summary><p>{desc}</p></details>' for i,(name,desc) in enumerate(items))
    return f'<section class="studio-section"><div class="container service-details-grid"><div class="sticky-copy"><p class="eyebrow">{kicker}</p><h2>{title}</h2><p>{introduction}</p></div><div class="studio-details">{rows}</div></div></section>'

def questions(h, items):
    return '<section class="studio-section faq-section"><div class="container service-details-grid"><div><p class="eyebrow">PRZED PIERWSZĄ ROZMOWĄ</p><h2>To warto<br><em>wiedzieć.</em></h2></div>'+h['faq'](items)+'</div></section>'

def sequence_controls(names):
    buttons=''.join(f'<button type="button" data-sequence-step="{i}" aria-pressed="{str(i==len(names)-1).lower()}"><span>0{i+1}</span>{n}</button>' for i,n in enumerate(names))
    return f'<div class="sequence-controls" hidden><div class="sequence-steps" role="group" aria-label="Etapy prezentacji">{buttons}</div><button class="sequence-play" type="button" data-sequence-play hidden>Odtwórz przemianę <span aria-hidden="true">▶</span></button></div>'

def architecture_canvas(compact=False):
    return f'''<div class="architecture-canvas" data-architecture>
<div class="architecture-image">{picture(priority=True)}{film()}</div>
<div class="architecture-grid" aria-hidden="true"></div>
<div class="architecture-nav"><span class="concept-wordmark">horyzont.</span><span>Architektura &nbsp; / &nbsp; Przestrzenie</span></div>
<div class="architecture-copy"><p class="eyebrow">DOM ZACZYNA SIĘ OD CIEBIE.</p><h3><span>Przestrzeń</span><br><em>ma znaczenie.</em></h3><p>Światło. Materiał. Twój sposób życia.</p><a href="/horyzont.html" class="architecture-link">Wejdź do środka <span aria-hidden="true">↗</span></a></div>
<div class="architecture-bottom"><span>DOM NAD MORZEM / KONCEPCJA</span><span>01 — 02</span></div>
<button type="button" class="film-toggle" data-film-toggle hidden>Wstrzymaj film Ⅱ</button>
</div>'''

def build_scene():
    return f'''<section class="build-scene" data-sequence="build" data-step="3" data-count="4" data-duration="1800" id="pokaz-strony">
<div class="container theatre-heading"><div><p class="eyebrow">STRONY WWW / OD POMYSŁU DO DOŚWIADCZENIA</p><h1>Wygląd to początek.<br><em>Liczy się doświadczenie.</em></h1></div><div><p>Przyciągnij uwagę. Pokaż swoją wartość. Ułatw klientowi następny krok.</p>{contact('Porozmawiajmy o stronie','Strona internetowa')}</div></div><div class="theatre-concept container"><span>HORYZONT / AUTORSKA KONCEPCJA</span><span>Zobacz, jak powstaje strona ↓</span></div>
<div class="build-stage container">{architecture_canvas()}<div class="build-mobile" aria-hidden="true">{picture()}<div><span>horyzont.</span><p>Przestrzeń<br><em>ma znaczenie.</em></p><b>Odkryj projekt ↗</b></div></div><div class="build-blueprint-label" aria-hidden="true">KIERUNEK / HIERARCHIA / UKŁAD</div></div>
<div class="container">{sequence_controls(['Plan','Obraz','Charakter','Gotowa strona'])}<div class="scene-caption"><p>Od uporządkowanego planu do strony, którą możesz otworzyć i sprawdzić.</p>{link('Otwórz cały przykład','/horyzont.html')}</div></div></section>'''

def campaign_scene(social=False):
    title='Twoja marka.<br>Warta <em>uwagi.</em>' if social else 'Niech o Tobie<br><em>usłyszą.</em>'
    return f'''<section class="campaign-scene campaign-opening" data-sequence="campaign" data-step="2" data-count="3" data-duration="2600" id="pokaz-kampanii"><div class="container scene-topline"><p class="eyebrow">{('SOCIAL MEDIA' if social else 'KAMPANIA')} / PRZYKŁAD KONCEPCYJNY</p><span>horyzont / architektura</span></div>
<div class="container campaign-heading"><p class="eyebrow">{('SOCIAL MEDIA / WŁASNY GŁOS' if social else 'MARKETING / DOBRY KIERUNEK')}</p><h1>{title}</h1><p>{('Pomysł, obraz i opowieść, do których chce się wracać. Zbudujmy obecność, którą odbiorcy rozpoznają.' if social else 'Dobra oferta zasługuje na uwagę. Łączymy reklamę, treści i stronę w jedną drogę do Twojej firmy.')}</p>{contact('Omówmy Twoje profile' if social else 'Zaplanujmy kampanię','Social media' if social else 'Marketing')}<p class="campaign-proof">Jedna koncepcja. Trzy punkty kontaktu.</p></div>
<div class="campaign-canvas container">
<div class="campaign-poster"><div class="poster-image">{picture()}{film('campaign-video')}</div><div class="poster-content"><span class="concept-wordmark">horyzont.</span><h3>Miejsce<br>na <em>Twoje życie.</em></h3><span class="poster-end">ARCHITEKTURA, KTÓRA ZACZYNA SIĘ OD CIEBIE. ↗</span></div><button type="button" data-film-toggle class="film-toggle" hidden>Wstrzymaj film Ⅱ</button></div>
<div class="campaign-wide"><div class="campaign-wide-image">{picture()}</div><div class="campaign-wide-copy"><span class="concept-wordmark">horyzont.</span><h3>Przestrzeń<br><em>ma znaczenie.</em></h3><a href="/horyzont.html">Odkryj projekt {ARROW}</a></div></div>
<div class="campaign-phone"><div class="campaign-phone-top"><span>horyzont.</span><span>•••</span></div>{picture('interior')}<div class="campaign-phone-body"><span>♡ &nbsp; ↗</span><p><strong>Dom, w którym zwalniasz.</strong><br>Światło i naturalne materiały. Resztę dopiszesz Ty.</p><a href="/horyzont.html">Poznaj tę przestrzeń ↗</a></div></div>
</div><div class="container">{sequence_controls(['Obraz','Opowieść','Następny krok'] if social else ['Zauważenie','Rozpoznanie','Kontakt'])}<div class="scene-caption"><p>Od jednego pomysłu do spójnej obecności: reklamy, strony i publikacji.</p>{contact('Taką spójność chcę u siebie',social and 'Social media' or 'Marketing',False)}</div></div></section>'''

def home_content():
    hero=spring_opening().replace('Daj swojej<br>marce<br><span>nowe życie.</span>','Daj się<br><em>zapamiętać.</em>').replace('Odważny początek albo nowy rozdział.<br>Zbudujmy go razem.','Budujemy marki od zera.<br>Istniejącym dajemy nową siłę.').replace('Zacznijmy nowy rozdział','Zobacz, co możemy zrobić').replace('href="/kontakt.html">Zobacz, co możemy zrobić','href="/oferta.html">Zobacz, co możemy zrobić').replace('href="/oferta.html">Poznaj ofertę','href="/realizacje.html">Zobacz projekty')
    hero=re.sub(r'<div class="button-row">.*?</div>', '', hero, count=1, flags=re.S)
    return hero+f'''<section class="studio-section home-manifesto" id="wybierz-kierunek"><div class="container manifesto-grid"><div><p class="eyebrow">DOBRA FIRMA ZASŁUGUJE NA DOBRY WIZERUNEK.</p><h2 data-reveal>Pokaż światu,<br><em>co potrafisz.</em></h2></div><div><p class="lead">Strona, marketing i narzędzia mogą pracować na tę samą markę. Zaczynamy od Twojej firmy. Łączymy to, co widzi klient, z tym, czego potrzebuje biznes.</p><div class="direction-choices"><a href="/o-donie.html#przemiana">Odnawiam istniejącą markę {ARROW}</a><a href="/o-donie.html#od-zera">Buduję markę od zera {ARROW}</a></div></div></div></section>
<section class="home-studio-showcase"><div class="container home-showcase-grid"><article class="home-work-preview" data-reveal><div class="home-work-art">{picture()}{film()}<div class="home-work-type"><span>horyzont.</span><p>Przestrzeń<br><em>ma znaczenie.</em></p></div><button type="button" class="film-toggle" data-film-toggle hidden>Ożyw obraz ▶</button><a class="image-action" href="/strony-www.html" aria-label="Zobacz pokaz powstawania strony">↗</a></div><a class="home-preview-caption" href="/strony-www.html"><div><p class="eyebrow">STRONY WWW / ZOBACZ POWSTAWANIE PROJEKTU</p><h3>Pomysł nabiera <em>formy.</em></h3></div><span aria-hidden="true">↗</span></a></article><a class="home-agent-preview" href="/automatyzacja.html" data-reveal><p class="eyebrow">DONA / TWÓJ CYFROWY ZESPÓŁ</p><h3>Ty tworzysz.<br><em>Rutyna robi się sama.</em></h3><div class="home-agent-story" aria-hidden="true"><span>Nowe zapytanie <b>↗</b></span><i></i><span>Gotowa propozycja odpowiedzi <b>✓</b></span><i></i><span>Twoja decyzja <b>→</b></span></div><span class="text-link">Zobacz agentów w działaniu {ARROW}</span></a></div></section>'''+closing(description='O stronie, z której chcesz być dumny. O marce, która ma się wyróżniać. Albo o pomyśle, który dopiero nabiera kształtu.')

def web_content(h):
    return heading('STRONY INTERNETOWE / STRATEGIA · DESIGN · WDROŻENIE','Zobacz, co może<br><em>Twoja strona.</em>','Zanim klient zadzwoni, sprawdzi Cię w internecie. Daj mu powód, żeby został — i wiedział, dlaczego warto wybrać Ciebie.',contact('Porozmawiajmy o stronie','Strona internetowa'))+build_scene()+details('KAŻDY ELEMENT MA ZADANIE.','Piękna forma.<br><em>Przemyślana droga.</em>',[
('Kierunek, który ma uzasadnienie','Poznajemy Twoją firmę i odbiorców. Układamy ofertę, hierarchię treści i drogę od wejścia na stronę do kontaktu.'),
('Charakter, który rozpoznajesz','Typografia, obrazy, kolor i ruch tworzą wspólną całość. Projekt pokazuje Twoją markę, a nie przypadkowy zestaw modnych efektów.'),
('Wygoda na każdym ekranie','Projektujemy osobno zachowanie na telefonie: menu, czytelność, animacje i formularze. Ważny przycisk ma być pod ręką.'),
('Uruchomienie i dalsza opieka','Wdrożenie, uzgodnione integracje, sprawdzenie kontaktu i podstaw widoczności. Możliwość samodzielnej edycji ustalamy przy wyborze technologii.')], 'Projekt obejmuje również to, co dzieje się po pierwszym „wow”.')+f'''<section class="studio-section renovation-link"><div class="container renovation-grid"><div class="renovation-image">{picture('interior')}</div><div><p class="eyebrow">MASZ JUŻ STRONĘ?</p><h2>Nie zaczynasz<br><em>z pustą kartką.</em></h2><p>Masz historię, klientów i doświadczenie. Sprawdzimy, co warto zachować, a co potrzebuje nowej formy.</p>{link('Zobacz nasze podejście','/o-donie.html')}{contact('Pokaż nam obecną stronę','Strona internetowa')}</div></div></section>'''+questions(h,[('Czy przygotujecie teksty i grafiki?','Tak, możemy uwzględnić je w zakresie. Potrzebujemy wiedzy o Twojej firmie i prawdziwych argumentów, które mają przekonać klienta.'),('Czy będę samodzielnie aktualizować stronę?','Jeżeli tego potrzebujesz, dobierzemy sposób edycji do Twojej pracy. Ustalamy go przed rozpoczęciem wdrożenia.'),('Ile kosztuje projekt i kiedy będzie gotowy?','Zakres, materiały, funkcje i termin wspólnie ustalamy przed wyceną. Otrzymujesz propozycję prac i harmonogram — bez zgadywania jednej ceny dla wszystkich firm.')])+closing('Strona internetowa')

def marketing_content(h, social=False):
    if social:
        return heading('SOCIAL MEDIA / OBRAZ · OPOWIEŚĆ · OBECNOŚĆ','Jedna marka.<br><em>Wszędzie rozpoznawalna.</em>','Pomagamy opowiadać o Twojej pracy tak, żeby kolejne publikacje budowały charakter marki i dawały odbiorcom powód do powrotu.',contact('Omówmy Twoje profile','Social media'))+campaign_scene(True)+details('OBECNOŚĆ Z POMYSŁEM.','Twój charakter.<br><em>W każdym formacie.</em>',[
('Zaczynamy od tego, co masz do powiedzenia','Poznajemy odbiorców, ich pytania i to, co naprawdę wyróżnia Twoją firmę. Z tego powstają tematy, język i plan publikacji.'),('Obrazy, które pracują razem','Projektujemy grafiki, karuzele i krótkie formaty wideo. Dopasowujemy materiał do miejsca publikacji, zachowując wspólną tożsamość marki.'),('Publikacje, nad którymi masz kontrolę','Uzgadniamy harmonogram i sposób akceptacji. Prowadzenie profilu oraz ewentualną obsługę wiadomości wyceniamy według konkretnego zakresu.'),('Wnioski do następnych materiałów','Sprawdzamy uzgodnione dane i reakcje odbiorców. Kolejne publikacje rozwijają to, co ma znaczenie dla Twojej marki.')])+questions(h,[('Czy muszę nagrywać siebie?','Nie zawsze. Możemy oprzeć komunikację na produkcie, realizacjach, procesie pracy lub innych uzgodnionych materiałach.'),('Czy zobaczę materiały przed publikacją?','Tak. Sposób akceptacji, terminy i zakres samodzielnego działania ustalamy przed rozpoczęciem współpracy.'),('Czy prowadzenie profilu obejmuje reklamy?','Płatne kampanie są osobnym zakresem. Jeśli potrzebujesz obu usług, połączymy je w jeden plan.')])+closing('Social media')
    return heading('MARKETING / STRATEGIA · KAMPANIE · POMIAR','Daj dobrej ofercie<br><em>dobry rozgłos.</em>','Łączymy kreację, reklamę i stronę po kliknięciu. Żeby klient rozumiał Twoją ofertę i miał prostą drogę do rozmowy.',contact('Zaplanujmy kampanię','Marketing'))+campaign_scene()+details('PLAN, KTÓRY ŁĄCZY DZIAŁANIA.','Właściwy przekaz.<br><em>Właściwy moment.</em>',[
('Poznajemy rynek i klienta','Badamy punkt wyjścia: ofertę, odbiorców, konkurencję i dotychczasowe działania. Wybieramy cel, który można ocenić.'),('Projektujemy całą drogę','Kreacja przyciąga uwagę. Strona rozwija tę samą obietnicę i pomaga podjąć decyzję. Kontakt domyka doświadczenie.'),('Dobieramy kanały','Google Ads, Meta Ads lub inny uzgodniony zakres. Wybór wynika z celu, budżetu i tego, gdzie klienci podejmują decyzje.'),('Mierzymy i wyciągamy wnioski','Ustalamy, jakie zdarzenia mają znaczenie, oraz porównujemy wyniki z kosztami. Obsługa i budżet emisji są rozliczane oddzielnie.')])+f'''<section class="studio-section marketing-bridge"><div class="container"><p class="eyebrow">KAMPANIA TO DOPIERO POCZĄTEK ROZMOWY.</p><h2 data-reveal>Reklama zainteresuje.<br><em>Co wydarzy się dalej?</em></h2><div class="bridge-links">{link('Strona, która rozwija obietnicę','/strony-www.html')}{link('Agenci, którzy porządkują zapytania','/automatyzacja.html')}</div></div></section>'''+questions(h,[('Czy gwarantujecie konkretną liczbę klientów?','Nie. Wyniki zależą od oferty, rynku, budżetu i obsługi zapytań. Ustalamy cel, sposób pomiaru i zakres odpowiedzialności.'),('Czy możecie przejąć obecne kampanie?','Zaczynamy od przeglądu konta i danych. Dopiero potem proponujemy, co zachować, zmienić i sprawdzić.'),('Jak ustalany jest budżet?','Oddzielamy koszt przygotowania i obsługi od pieniędzy przeznaczonych na emisję. Zakres i budżet dobieramy po poznaniu sytuacji.')])+closing('Marketing')

def offer_content(h):
    options=[('Strona internetowa','Chcę lepszą stronę.'),('Nowa marka','Buduję markę od zera.'),('Odnowa marki','Czas odnowić wizerunek.'),('Marketing','Chcę dotrzeć do klientów.'),('Automatyzacja','Chcę odzyskać czas.')]
    buttons=''.join(f'<button type="button" data-offer-option="{i}" aria-pressed="{str(i==0).lower()}"><span>0{i+1}</span>{label}{ARROW}</button>' for i,(_,label) in enumerate(options))
    return heading('OFERTA / ZACZNIJ OD TEGO, CO MA SIĘ ZMIENIĆ.','Twój cel.<br><em>Nasz punkt wyjścia.</em>','Możemy stworzyć jeden element albo połączyć strategię, wizerunek, stronę i marketing. Wybierz sytuację najbliższą Twojej.',link('Mam już brief — zapytaj o wycenę','/wycena.html'))+f'''<section class="offer-workbench studio-section" data-offer><div class="container offer-workbench-grid"><div class="offer-options" role="group" aria-label="Wybierz cel współpracy">{buttons}</div><div class="offer-result" tabindex="0" aria-label="Proponowany punkt wyjścia"><div class="offer-result-image">{picture()}<span data-offer-kind>STRATEGIA / DESIGN / WDROŻENIE</span></div><div class="offer-result-body"><p class="sr-only" data-offer-announcement role="status"></p><h2 data-offer-title>Strona, która pokazuje<br><em>Twoją wartość.</em></h2><p data-offer-description>Zaczniemy od oferty i odbiorców. Zaprojektujemy oprawę oraz drogę od pierwszego wrażenia do zapytania.</p><p class="offer-deliverable" data-offer-result>Efekt prac: treści, projekt i działająca strona w uzgodnionym zakresie.</p><div class="button-row"><a class="button primary" href="/kontakt.html?temat=Strona%20internetowa" data-offer-contact>Omówmy ten kierunek {ARROW}</a><a class="text-link" href="/strony-www.html" data-offer-more>Zobacz więcej {ARROW}</a></div></div></div></div></section>
<section class="studio-section offer-directory" id="strategia"><div class="container"><p class="eyebrow">MOŻLIWOŚCI, KTÓRE MOŻEMY POŁĄCZYĆ.</p><h2>Od pierwszej myśli<br><em>do pierwszego kontaktu.</em></h2><div class="studio-service-links"><a href="/o-donie.html#od-zera"><span>01 / FUNDAMENT</span><h3>Research i strategia</h3><p>Odbiorcy, rynek, pozycjonowanie, plan.</p>{ARROW}</a><a href="/strony-www.html"><span>02 / DOŚWIADCZENIE</span><h3>Strony internetowe</h3><p>Treści, projekt, ruch i wdrożenie.</p>{ARROW}</a><a href="/marketing.html"><span>03 / DOTARCIE</span><h3>Marketing i kampanie</h3><p>Przekaz, reklama, strona i pomiar.</p>{ARROW}</a><a href="/social-media.html"><span>04 / OBECNOŚĆ</span><h3>Social media</h3><p>Plan, grafiki, wideo i publikacje.</p>{ARROW}</a><a href="/automatyzacja.html"><span>05 / CODZIENNA PRACA</span><h3>Agenci i automatyzacje</h3><p>Procesy, integracje i kontrola.</p>{ARROW}</a><a href="/akademia.html"><span>06 / NOWE UMIEJĘTNOŚCI</span><h3>Akademia AI</h3><p>Wiedza do wykorzystania w Twojej pracy.</p>{ARROW}</a></div></div></section>'''+questions(h,[('Czy muszę zamawiać wszystko?','Nie. Zakres może obejmować pojedynczą usługę. Łączymy działania, kiedy wspólnie pomagają osiągnąć Twój cel.'),('Od czego zależy cena?','Od zakresu prac, liczby materiałów, funkcji i integracji. Najpierw poznajemy potrzeby, potem przedstawiamy konkretną propozycję.'),('Jak wygląda pierwszy kontakt?','Opowiedz krótko o firmie i planowanej zmianie. Ustalimy pytania, punkt wyjścia i następny krok.')])+closing()

def live_embed(url, name, uid):
    return f'''<div class="live-site-preview container" data-live-site data-site-url="{url}" data-site-title="{name}"><div class="live-preview-toolbar"><div><span class="eyebrow">WEJDŹ DO ŚRODKA</span><p>Sprawdź prawdziwą stronę w tej prezentacji.</p></div><div class="button-row"><button type="button" class="button dark" data-open-live aria-expanded="false" aria-controls="{uid}">Otwórz podgląd {ARROW}</button><a class="text-link" href="{url}" target="_blank" rel="noopener">Otwórz w nowej karcie {ARROW}</a></div></div><p class="external-site-notice">Podgląd połączy Cię z serwisem {name}, który może korzystać z własnych cookies. <a href="/cookies.html#podglady">Informacje o podglądach</a>.</p><div class="live-site-frame" id="{uid}" hidden><p class="live-frame-status" data-frame-status role="status">Ładowanie serwisu… Możesz też skorzystać z osobnej karty.</p><div data-frame-slot></div></div></div>'''

def projects_content(h):
    live=live_projects('serwisy',False)
    # Each real website is loaded only after the visitor chooses to open it.
    marker='<div class="container live-foot">'
    first=live.find(marker)
    live=live[:first]+live_embed('https://www.edwardjanusz.pl/','Edward Janusz','janusz-live-frame')+live[first:]
    second=live.rfind(marker)
    live=live[:second]+live_embed('https://www.silverandglass.pl/','Silver & Glass','silver-live-frame')+live[second:]
    return heading('PROJEKTY / ZOBACZ · DOTKNIJ · ODKRYJ','Historie, do których<br><em>chce się wejść.</em>','Każdy biznes potrzebuje własnej formy. Obejrzyj działające serwisy, sprawdź interakcje i poznaj przykłady dla różnych branż.',contact('Stwórzmy Twój projekt'))+f'''<div class="container project-filter-shell"><div class="filter-row" role="group" aria-label="Filtruj projekty"><button data-project-filter="all" aria-pressed="true">Wszystkie</button><button data-project-filter="live" aria-pressed="false">Działające serwisy</button><button data-project-filter="uslugi" aria-pressed="false">Usługi</button><button data-project-filter="beauty" aria-pressed="false">Beauty</button><button data-project-filter="gastro" aria-pressed="false">Gastronomia</button></div><p class="filter-status" data-filter-status role="status">Widoczne projekty: 8</p></div>'''+live+f'''<section class="studio-section demo-collection" data-demo-collection><div class="container"><div class="demo-heading"><div><p class="eyebrow">PROJEKTY DEMONSTRACYJNE</p><h2>Różne branże.<br><em>Różne charaktery.</em></h2></div><p>Przykładowe marki. Działające strony, które możesz otworzyć i sprawdzić.</p></div><div class="project-grid">{h['project_cards']()}</div></div></section>'''+closing(description='Twoja firma nie musi przypominać żadnego z tych przykładów. Zaprojektujmy jej własny charakter.')

def approach_content():
    car=restoration_scene().replace('Charakter zostaje.<br><span>Reszta nabiera blasku.</span>','Wydobywamy<br><em>to, co najlepsze.</em>').replace('Tak myślimy o nowym rozdziale Twojej firmy.','Poznajemy. Porządkujemy. Budujemy na nowo.')
    return car+brand_foundation()+details('JASNY PROCES WSPÓŁPRACY.','Wiesz, co powstaje.<br><em>Masz na to wpływ.</em>',[('Poznajemy punkt wyjścia','Rozmawiamy o firmie, odbiorcach i celu. Ustalamy zakres oraz potrzebne materiały.'),('Pokazujemy kierunek','Otrzymujesz projekt do obejrzenia i omówienia. Podejmujemy decyzje, zanim przejdziemy do kolejnego etapu.'),('Łączymy i sprawdzamy','Składamy treści, projekt i funkcje. Testujemy uzgodnione ścieżki, kontakt i zachowanie na różnych ekranach.'),('Uruchamiamy i planujemy dalszy rozwój','Przekazujemy gotowy zakres i ustalenia dotyczące obsługi. Kolejne działania wynikają z Twoich potrzeb oraz obserwacji.')])+closing('Nowa marka',description='Firma z historią czy pomysł na nową? W obu przypadkach zaczynamy od dobrego poznania tematu.')

def automation_content(h):
    scene=flow_scene('workflow-explorer',hero=True,initial='media')
    a=scene.index('<div class="flow-heading');b=scene.index('<div class="flow-toolbar',a)
    scene=scene[:a]+'''<div class="flow-heading container"><div><p class="eyebrow">DONA / TWÓJ CYFROWY ZESPÓŁ</p><h1>Zobacz, jak<br><em>pracują agenci.</em></h1></div><div class="flow-intro"><p>Wiadomość. Materiał wideo. Pomysł na stronę. Jeden impuls uruchamia kolejne działania.</p><p>Wybierz proces i dotknij dowolnego etapu.</p>'''+contact('Omówmy Twój proces','Automatyzacja')+'</div></div>'+scene[b:]
    return scene+details('OD ZADANIA DO GOTOWEGO REZULTATU.','Oddaj rutynę.<br><em>Zachowaj kontrolę.</em>',[('Poczta, która nie gubi kontekstu','System rozpoznaje temat, zbiera informacje i przygotowuje propozycję odpowiedzi. W pokazanym procesie wysyłka wymaga zatwierdzenia.'),('Materiały, które trafiają dalej','Gałąź mediów pomaga analizować materiał, opracować go i przekazać do kolejnych zadań. Wybierasz zakres potrzebny w swojej pracy.'),('Proces, który możesz zrozumieć','Uzgadniamy źródła danych, dozwolone działania i miejsca wymagające Twojej decyzji. Wyjaśniamy całość bez konieczności czytania technicznego schematu.'),('Mały start, sprawdzalne działanie','Wybieramy jedno zadanie, podłączamy narzędzia i testujemy przebieg oraz błędy. Rozbudowa ma sens po sprawdzeniu pierwszego zakresu.')], 'Pokazy działają na danych przykładowych. Niczego nie wysyłają i nie uruchamiają na kontach klientów.')+questions(h,[('Czy muszę zmieniać programy używane w firmie?','Najpierw sprawdzamy możliwości połączenia obecnych narzędzi. Integracje i uprawnienia ustalamy przed deklarowaniem zakresu.'),('Czy agent może się pomylić?','Tak. Dlatego projekt obejmuje kontrolę, sytuacje wyjątkowe i zasady przekazywania decyzji człowiekowi.'),('Jak wygląda koszt wdrożenia?','Oddzielamy przygotowanie procesu od kosztów narzędzi, użycia modeli i opieki. Wycena powstaje po poznaniu zadania.')])+closing('Automatyzacja','Co robisz ręcznie<br><em>po raz setny?</em>','Opisz jedno powtarzalne zadanie. Sprawdźmy, czy warto je zautomatyzować.')

def prompt_lab():
    return '''<section class="prompt-lab studio-section" data-prompt-lab><div class="container prompt-lab-grid"><div><p class="eyebrow">SPRÓBUJ NA PROSTYM PRZYKŁADZIE.</p><h2>Lepsze pytanie.<br><em>Lepszy początek.</em></h2><p>Wybierz zadanie. Zobacz, jak cel, kontekst i format zmieniają ogólne polecenie w użyteczny punkt wyjścia.</p><div class="prompt-options" role="group" aria-label="Wybierz przykład polecenia"><button type="button" data-prompt-option="mail" aria-pressed="true">Odpowiedź klientowi ↗</button><button type="button" data-prompt-option="social" aria-pressed="false">Pomysły na publikacje ↗</button><button type="button" data-prompt-option="research" aria-pressed="false">Plan researchu ↗</button></div></div><div class="prompt-sheet"><span class="prompt-sheet-label">TWÓJ WARSZTAT / PRZYKŁAD</span><p class="prompt-before" data-prompt-before>„Napisz odpowiedź na e-mail.”</p><div class="prompt-refinement"><span>CEL</span><p data-prompt-goal>Przygotuj uprzejmy szkic odpowiedzi na zapytanie o usługę.</p><span>KONTEKST</span><p data-prompt-context>Wkleję wiadomość klienta i informacje o ofercie. Używaj tylko tych danych. Wskaż, czego brakuje.</p><span>FORMAT I KONTROLA</span><p data-prompt-format>Zwróć szkic do 120 słów oraz pytania do wyjaśnienia. Nie wymyślaj ceny ani terminu. Niczego nie wysyłaj.</p></div><button type="button" data-prompt-copy class="button dark">Skopiuj polecenie ↗</button><p class="form-note" data-prompt-status role="status">To przykład polecenia do samodzielnego użycia. Nie uruchamia modelu AI.</p><textarea data-prompt-export class="prompt-export" aria-label="Polecenie do skopiowania" readonly hidden></textarea></div></div></section>'''

def academy_content():
    return heading('AKADEMIA AI / PRAKTYCZNE UMIEJĘTNOŚCI','Z „nie wiem jak”<br><em>w „potrafię”.</em>','Ucz się narzędzi na zadaniach, które znasz z pracy. Przygotuj polecenie, opracuj materiał, zaplanuj proces — i naucz się sprawdzać rezultat.',contact('Zapytaj o program i dostęp','Akademia AI'))+prompt_lab()+details('WIEDZA, KTÓREJ UŻYWASZ.','Poznajesz.<br>Robisz.<br><em>Sprawdzasz.</em>',[('Asystenci AI i codzienna praca','Formułowanie poleceń, przekazywanie kontekstu, praca z informacją i weryfikacja odpowiedzi.'),('Treści, grafika i wideo','Pomysły i praktyczne przygotowanie materiałów z użyciem uzgodnionych narzędzi.'),('Automatyzacja procesów','Jak rozpoznać powtarzalne zadanie i połączyć narzędzia wokół konkretnego celu.')], 'O aktualny program, zawartość i warunki dostępu zapytaj przed zakupem.')+f'''<section class="studio-section academy-entry"><div class="container"><p class="eyebrow">MASZ JUŻ DOSTĘP?</p><h2>Wracaj<br><em>do tworzenia.</em></h2>{link('Otwórz platformę Akademii','https://akademia.probatum.pl/',True)}</div></section>'''+closing('Akademia AI',description='Napisz, czym się zajmujesz i czego chcesz się nauczyć. Dobierzmy właściwy początek.')

def journal_content(h, workshop=False):
    intro=heading('WIEDZA / '+('WARSZTAT' if workshop else 'PERSPEKTYWY'), 'Z wiedzy<br><em>zrób użytek.</em>' if workshop else 'Zanim zrobisz ruch,<br><em>zobacz więcej.</em>', 'Małe zadanie, jasna kolejność i rezultat do sprawdzenia.' if workshop else 'O stronach, komunikacji i technologii przez pryzmat decyzji, które podejmujesz w swojej firmie.')
    title='Nowe zapytanie prosto na telefon.' if workshop else 'Po co małej firmie agent AI?'
    url='/warsztat/pierwsza-automatyzacja.html' if workshop else '/blog/po-co-agent-malej-firmie.html'
    graphic='''<div class="editorial-process" aria-hidden="true" data-editorial-motion><span>01 / NOWE ZAPYTANIE</span><p>„Porozmawiajmy<br>o projekcie.”</p><i>↓</i><span>02 / PRZYGOTOWANE INFORMACJE</span><p>Wiesz, kto pisze.<br>Wiesz, czego potrzebuje.</p><i>↓</i><span>03 / TWÓJ NASTĘPNY KROK</span><p class="editorial-result">Możesz <em>odpowiedzieć.</em></p></div>'''
    return intro+f'''<section class="studio-section pad-top-zero"><div class="container">{h['editorial_nav'](workshop)}<article class="editorial-feature"><a class="editorial-visual" href="{url}" aria-label="Przeczytaj: {title}">{graphic}<span class="image-action" aria-hidden="true">↗</span></a><div class="editorial-feature-copy"><p class="eyebrow">{('PIERWSZY PROCES / INSTRUKCJA' if workshop else 'AUTOMATYZACJA / PERSPEKTYWA')}</p><h2>{title}</h2><p>{('Zaplanuj drogę od formularza do powiadomienia. Sprawdź dane, odbiorcę i sytuacje wyjątkowe.' if workshop else 'Jak rozpoznać proces, który warto usprawnić? I kiedy wystarczy prosta automatyzacja?')}</p>{link('Otwórz materiał',url,True)}<span class="editorial-note">Prosto. Z konkretnym zastosowaniem.</span></div></article></div></section>'''+closing('Automatyzacja',description='Masz podobny problem w swojej firmie? Opisz, co dziś robisz ręcznie.')

def concept_content():
    return f'''<div class="concept-notice"><div class="container"><span>HORYZONT / PROJEKT KONCEPCYJNY PROBATUM</span>{link('Omów podobny projekt','/kontakt.html?temat=Strona%20internetowa')}</div></div><section class="concept-home"><div class="concept-backdrop">{picture(priority=True)}{film()}</div><div class="container concept-top"><span class="concept-wordmark">horyzont.</span><nav aria-label="Menu projektu koncepcyjnego"><a href="#przestrzen">Przestrzeń</a><a href="#wnetrze">Wnętrze</a><a href="#o-projekcie">O projekcie</a></nav></div><div class="container concept-main"><p class="eyebrow">DOM ZACZYNA SIĘ OD CIEBIE.</p><h1>Przestrzeń<br><em>ma znaczenie.</em></h1><p>Światło. Materiał. Twój sposób życia.</p><a class="concept-enter" href="#przestrzen">Wejdź do środka <span aria-hidden="true">↓</span></a></div><button type="button" data-film-toggle class="film-toggle" hidden>Wstrzymaj film Ⅱ</button><div class="container concept-bottom"><span>DOM NAD MORZEM</span><span>KONCEPCJA ARCHITEKTONICZNA</span></div></section>
<section class="concept-story studio-section" id="przestrzen"><div class="container concept-story-grid"><div><p class="eyebrow">01 / PRZESTRZEŃ</p><h2>Najlepszy widok?<br><em>Twój własny.</em></h2></div><p>Dom otwiera się na światło i krajobraz. Prosta forma pozwala wybrzmieć materiałom. Przestrzeń zostawia miejsce na życie.</p></div><div class="concept-landscape" data-reveal>{picture()}</div></section>
<section class="concept-interior studio-section" id="wnetrze"><div class="container concept-interior-grid"><div class="concept-interior-image" data-reveal>{picture('interior',alt='Koncepcyjne wnętrze: światło, jasny kamień i oliwkowy fotel')}</div><div><p class="eyebrow">02 / WNĘTRZE</p><h2>Mniej pośpiechu.<br><em>Więcej przestrzeni.</em></h2><p>Naturalne materiały, miękkie światło i otwarcie na zewnątrz. Wnętrze zaprojektowane wokół codziennych rytuałów.</p><a class="text-link" href="#o-projekcie">Poznaj tę koncepcję {ARROW}</a></div></div></section>
<section class="concept-about studio-section" id="o-projekcie"><div class="container service-details-grid"><div><p class="eyebrow">KONCEPCJA CYFROWEGO DOŚWIADCZENIA</p><h2>Wyobraź sobie<br><em>Twoją markę tutaj.</em></h2></div><div><p class="lead">Horyzont to fikcyjna marka stworzona, by pokazać sposób projektowania strony i spójnej kampanii. Architektura i film są materiałami koncepcyjnymi wygenerowanymi z AI.</p><p>Twoją stronę oprzemy na Twojej firmie, jej ofercie i uzgodnionych materiałach.</p>{contact('Zaprojektujmy Twoją stronę','Strona internetowa')}{link('Zobacz koncepcję kampanii','/marketing.html')}</div></div></section>'''

def apply_studio(pages, h):
    replacements={
      'index.html':home_content(), 'oferta.html':offer_content(h),
      'strony-www.html':web_content(h), 'marketing.html':marketing_content(h),
      'social-media.html':marketing_content(h,True), 'realizacje.html':projects_content(h),
      'o-donie.html':approach_content(), 'automatyzacja.html':automation_content(h),
      'akademia.html':academy_content(), 'blog.html':journal_content(h),
      'warsztat.html':journal_content(h,True)
    }
    for path,marker in [('strony-www.html','<section class="build-scene"'),('marketing.html','<section class="campaign-scene'),('social-media.html','<section class="campaign-scene')]:
        replacements[path]=replacements[path][replacements[path].index(marker):]
    academy=replacements['akademia.html']
    academy=academy[academy.index('<section class="prompt-lab'):]
    academy=academy.replace('<p class="eyebrow">SPRÓBUJ NA PROSTYM PRZYKŁADZIE.</p><h2>Lepsze pytanie.<br><em>Lepszy początek.</em></h2>', '<p class="eyebrow">AKADEMIA AI / SPRÓBUJ, A ZROZUMIESZ.</p><h1>Z „nie wiem jak”<br><em>w „potrafię”.</em></h1>')
    academy=academy.replace('<div class="prompt-options"', contact('Zapytaj o program','Akademia AI')+'<div class="prompt-options"')
    replacements['akademia.html']=academy
    for path,body in replacements.items():
        title,desc,_,cls=pages[path]
        pages[path]=(title,desc,body,cls)
    for path in ['kontakt.html','wycena.html']:
        title,desc,body,cls=pages[path]
        start=body.index('<section class="section pad-top-zero">')
        body=body[start:]
        # Keep the renovation choice distinct so service links prefill the right intent.
        needle='<span>Nowa marka</span></label>'
        body=body.replace(needle, needle+'<label class="choice"><input type="radio" name="usluga" value="Odnowa marki"><span>Odnowa marki</span></label>')
        new_heading=heading('KONTAKT / ZACZNIJMY OD ROZMOWY' if path=='kontakt.html' else 'ZAPYTANIE O WYCENĘ / TRZY KRÓTKIE KROKI', 'Co ma się<br><em>zmienić?</em>' if path=='kontakt.html' else 'Nadajmy pomysłowi<br><em>konkretny kształt.</em>', 'Opowiedz o swojej firmie. Wystarczą dwa zdania o tym, gdzie jesteś i dokąd chcesz dojść.',link('Zadzwoń: +48 573 569 141','tel:+48573569141',True))
        pages[path]=(title,desc,new_heading+body,cls)
    for path in ['blog/po-co-agent-malej-firmie.html','warsztat/pierwsza-automatyzacja.html']:
        title,desc,body,cls=pages[path]
        body=body.split('<section class="big-close">')[0]+closing('Automatyzacja')
        pages[path]=(title,desc,body,cls)
    _,_,home,cls=pages['index.html']
    pages['index.html']=('Probatum — daj się zapamiętać. Strony, marki i marketing.','Budujemy marki od zera, istniejącym dajemy nową siłę. Strategia, strony internetowe, marketing i automatyzacje Probatum.',home,cls)
    pages['horyzont.html']=('Horyzont — koncepcyjny projekt strony | Probatum','Interaktywny przykład strony architektonicznej i spójnej komunikacji. Projekt koncepcyjny Probatum.',concept_content(),'concept')
